Repository googleapis/java-asset, pull requests merged in 2020-12, with the labels that each got.

#459 samples: Add samples for AnalyzerIamPolicy and AnalyzeIamPolicyLongrunning
  samples/snippets/src/main/java/com/example/asset/AnalyzeIamPolicyExample.java
  samples/snippets/src/main/java/com/example/asset/AnalyzeIamPolicyLongrunningBigqueryExample.java
  samples/snippets/src/main/java/com/example/asset/AnalyzeIamPolicyLongrunningGcsExample.java
  samples/snippets/src/test/java/com/example/asset/Analyze.java
Labels: api: cloudasset, cla: yes, samples

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#476 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#471 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#480 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#483 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#493 feat: deprecate v1beta1 client endpoint is turned down
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1beta1/stub/GrpcAssetServiceStub.java
  grpc-google-cloud-asset-v1beta1/src/main/java/com/google/cloud/asset/v1beta1/AssetServiceGrpc.java
  synth.metadata
  synth.py
Labels: api: cloudasset, automerge, cla: yes

#494 chore: migrate to microgenerator
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p1beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p1beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p1beta1/MockAssetServiceImpl.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p2beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p2beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p2beta1/MockAssetServiceImpl.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p4beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p4beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p4beta1/MockAssetServiceImpl.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/MockAssetServiceImpl.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BigQueryDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BigQueryDestinationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/FeedName.java
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  proto-google-cloud-asset-v1p2beta1/src/main/java/com/google/cloud/asset/v1p2beta1/FeedName.java
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full

#495 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#498 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudasset, cla: yes, context: full
