Repository googleapis/java-asset, pull requests merged in 2020-10, with the labels that each got.

#372 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#374 build: auto-approve README autosynth
  .github/workflows/approve-readme.yaml
Labels: api: cloudasset, cla: yes

#376 build: fix syntax error in approve-readme.yaml
  .github/workflows/approve-readme.yaml
Labels: cla: yes

#378 build: fix approve readme - need to paginate over endpoint
  .github/workflows/approve-readme.yaml
Labels: cla: yes

#380 build: fix synth.metadata path
  .github/workflows/approve-readme.yaml
Labels: automerge, cla: yes

#381 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, context: none

#395 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#397 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#401 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#408 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#399 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full, samples

#414 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#412 chore: regenerate common templates
  .github/snippet-bot.yml
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  renovate.json
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#417 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#418 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#429 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#431 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
