Repository googleapis/java-asset, pull requests merged in 2020-09, with the labels that each got.

#308 chore: regenerate README
  README.md
  synth.metadata
Labels: api: cloudasset, cla: yes, context: none

#324 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#325 feat!(v1): add support for per type and partition export, remove AnalyzeIamPolicy/ExportIamPolicyAnalysis
  google-cloud-asset/clirr-ignored-differences.xml
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  grpc-google-cloud-asset-v1/clirr-ignored-differences.xml
  grpc-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceGrpc.java
  proto-google-cloud-asset-v1/clirr-ignored-differences.xml
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BigQueryDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BigQueryDestinationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisOutputConfig.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisOutputConfigOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQuery.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQueryOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisResult.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisResultOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisState.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisStateOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/PartitionSpec.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/PartitionSpecOrBuilder.java
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/assets.proto
  synth.metadata
Labels: cla: yes, context: partial

#345 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#346 build: testing Yoshi Approver account token
  .github/workflows/auto-release.yaml
Labels: cla: yes

#352 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudasset, automerge, cla: yes

#360 chore: regenerate common templates
  .github/workflows/auto-release.yaml
  README.md
  synth.metadata
Labels: api: cloudasset, cla: yes, context: partial

#361 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#362 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#365 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
