Repository googleapis/java-asset, pull requests merged in 2020-07, with the labels that each got.

#246 feat(v1p5beta1): add v1p5beta1 client
  google-cloud-asset-bom/pom.xml
  google-cloud-asset/pom.xml
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p5beta1/MockAssetServiceImpl.java
  grpc-google-cloud-asset-v1p4beta1/clirr-ignored-differences.xml
  grpc-google-cloud-asset-v1p5beta1/pom.xml
  grpc-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceGrpc.java
  pom.xml
  proto-google-cloud-asset-v1p5beta1/clirr-ignored-differences.xml
  proto-google-cloud-asset-v1p5beta1/pom.xml
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/Asset.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/AssetOrBuilder.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/AssetProto.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceProto.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ContentType.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ListAssetsRequest.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ListAssetsRequestOrBuilder.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ListAssetsResponse.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ListAssetsResponseOrBuilder.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/Resource.java
  proto-google-cloud-asset-v1p5beta1/src/main/java/com/google/cloud/asset/v1p5beta1/ResourceOrBuilder.java
  proto-google-cloud-asset-v1p5beta1/src/main/proto/google/cloud/asset/v1p5beta1/asset_service.proto
  proto-google-cloud-asset-v1p5beta1/src/main/proto/google/cloud/asset/v1p5beta1/assets.proto
  synth.metadata
  synth.py
  versions.txt
Labels: cla: yes

#247 samples: fix sample dependencies
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#249 ci(java): run dependency tests on Java 8 & 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  pom.xml
  synth.metadata
Labels: cla: yes, context: none

#251 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#265 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#269 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
