Repository googleapis/java-asset, pull requests merged in 2020-08, with the labels that each got.

#277 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#279 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#289 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#297 samples: add lint presubmit checks
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#300 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /asset/cloud-client
  samples/snippets/src/main/java/com/example/asset/ListAssetsExample.java
  samples/snippets/src/test/java/com/example/asset/ListAssets.java
Labels: api: cloudasset, cla: yes

#301 feat(v1): add AnalyzeIamPolicy and ExportIamPolicyAnalysis RPCs
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  grpc-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceGrpc.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AnalyzeIamPolicyResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportIamPolicyAnalysisResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisOutputConfig.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisOutputConfigOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQuery.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQueryOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisResult.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisResultOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisState.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisStateOrBuilder.java
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/assets.proto
  synth.metadata
Labels: cla: yes, context: full
