Repository googleapis/java-asset, pull requests merged in 2020-06, with the labels that each got.

#194 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#197 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#200 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#202 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#208 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#213 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#219 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#220 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-asset/pom.xml
  grpc-google-cloud-asset-v1/pom.xml
  grpc-google-cloud-asset-v1beta1/pom.xml
  grpc-google-cloud-asset-v1p1beta1/pom.xml
  grpc-google-cloud-asset-v1p2beta1/pom.xml
  grpc-google-cloud-asset-v1p4beta1/pom.xml
  pom.xml
  proto-google-cloud-asset-v1/pom.xml
  proto-google-cloud-asset-v1beta1/pom.xml
  proto-google-cloud-asset-v1p1beta1/pom.xml
  proto-google-cloud-asset-v1p2beta1/pom.xml
  proto-google-cloud-asset-v1p4beta1/pom.xml
Labels: cla: yes

#226 feat(v1): add condition to Feed
  README.md
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  grpc-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceGrpc.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Asset.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BatchGetAssetsHistoryRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/BigQueryDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ExportAssetsResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Feed.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/FeedOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestinationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/OutputConfig.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/OutputConfigOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/PubsubDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/PubsubDestinationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Resource.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ResourceOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TemporalAsset.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/TemporalAssetOrBuilder.java
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/assets.proto
  synth.metadata
Labels: automerge, cla: yes, context: partial

#238 fix: migrate to grpc_service_config
  README.md
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#241 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
