Repository googleapis/java-asset, pull requests merged in 2021-05, with the labels that each got.

#686 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: none

#687 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudasset, automerge, cla: yes

#688 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#692 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#694 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#696 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#702 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#705 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#709 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#712 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#623 fix: close out todo for 2.0.0
  proto-google-cloud-asset-v1/clirr-ignored-differences.xml
Labels: api: cloudasset, cla: yes

#715 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#720 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#721 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#719 feat: add Cloud Asset List API
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/gapic_metadata.json
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/MockAssetServiceImpl.java
  grpc-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceGrpc.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/Asset.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/AssetServiceProto.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ConditionEvaluation.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ConditionEvaluationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestination.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/GcsDestinationOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisOutputConfig.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQuery.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisQueryOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicyAnalysisResult.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicySearchResult.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/IamPolicySearchResultOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ListAssetsRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ListAssetsRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ListAssetsResponse.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ListAssetsResponseOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ResourceSearchResult.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/ResourceSearchResultOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/SearchAllIamPoliciesRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/SearchAllIamPoliciesRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/SearchAllResourcesRequest.java
  proto-google-cloud-asset-v1/src/main/java/com/google/cloud/asset/v1/SearchAllResourcesRequestOrBuilder.java
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/asset_service.proto
  proto-google-cloud-asset-v1/src/main/proto/google/cloud/asset/v1/assets.proto
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#723 feat: add v1p7beta1 client
  google-cloud-asset-bom/pom.xml
  google-cloud-asset/pom.xml
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/gapic_metadata.json
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/package-info.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p7beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p7beta1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p7beta1/MockAssetService.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p7beta1/MockAssetServiceImpl.java
  grpc-google-cloud-asset-v1p7beta1/pom.xml
  grpc-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/AssetServiceGrpc.java
  pom.xml
  proto-google-cloud-asset-v1p7beta1/clirr-ignored-differences.xml
  proto-google-cloud-asset-v1p7beta1/pom.xml
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/Asset.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/AssetOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/AssetProto.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/AssetServiceProto.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/BigQueryDestination.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/BigQueryDestinationOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ContentType.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ExportAssetsRequest.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ExportAssetsRequestOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ExportAssetsResponse.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ExportAssetsResponseOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/GcsDestination.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/GcsDestinationOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/GcsOutputResult.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/GcsOutputResultOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/OutputConfig.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/OutputConfigOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/OutputResult.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/OutputResultOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/PartitionSpec.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/PartitionSpecOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelatedAsset.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelatedAssetOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelatedAssets.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelatedAssetsOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelationshipAttributes.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/RelationshipAttributesOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/Resource.java
  proto-google-cloud-asset-v1p7beta1/src/main/java/com/google/cloud/asset/v1p7beta1/ResourceOrBuilder.java
  proto-google-cloud-asset-v1p7beta1/src/main/proto/google/cloud/asset/v1p7beta1/asset_service.proto
  proto-google-cloud-asset-v1p7beta1/src/main/proto/google/cloud/asset/v1p7beta1/assets.proto
  samples/snippets/src/main/java/com/example/asset/BatchGetAssetsHistoryExample.java
  samples/snippets/src/main/java/com/example/asset/CreateFeedExample.java
  samples/snippets/src/main/java/com/example/asset/ListAssetsExample.java
  samples/snippets/src/main/java/com/example/asset/SearchAllResourcesExample.java
  samples/snippets/src/main/java/com/example/asset/UpdateFeedExample.java
  synth.metadata
  synth.py
  versions.txt
Labels: api: cloudasset, automerge, cla: yes

#724 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.py
Labels: api: cloudasset, automerge, cla: yes

#725 chore: start tracking obsolete files
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full
