Repository googleapis/java-asset, pull requests merged in 2021-01, with the labels that each got.

#499 chore(samples): remove unused import from sample
  samples/snippets/src/main/java/com/example/asset/DeleteFeedExample.java
  samples/snippets/src/main/java/com/example/asset/GetFeedExample.java
  samples/snippets/src/main/java/com/example/asset/ListAssetsExample.java
  samples/snippets/src/main/java/com/example/asset/ListFeedsExample.java
  samples/snippets/src/main/java/com/example/asset/UpdateFeedExample.java
  samples/snippets/src/test/java/com/example/asset/ListAssets.java
  samples/snippets/src/test/java/com/example/asset/RealTimeFeed.java
Labels: api: cloudasset, cla: yes, samples

#501 chore: update gapic-generator-java to 0.0.16
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1/AssetServiceClientTest.java
  google-cloud-asset/src/test/java/com/google/cloud/asset/v1p4beta1/AssetServiceClientTest.java
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#507 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#512 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#513 chore: update gapic-generator-java to 0.0.18
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p1beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p2beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p4beta1/stub/GrpcAssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceClient.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/AssetServiceSettings.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/AssetServiceStub.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceCallableFactory.java
  google-cloud-asset/src/main/java/com/google/cloud/asset/v1p5beta1/stub/GrpcAssetServiceStub.java
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#500 refactor(samples): restore stdout to original state in test
  samples/snippets/src/test/java/com/example/asset/Analyze.java
  samples/snippets/src/test/java/com/example/asset/ListAssets.java
  samples/snippets/src/test/java/com/example/asset/QuickStartIT.java
  samples/snippets/src/test/java/com/example/asset/RealTimeFeed.java
  samples/snippets/src/test/java/com/example/asset/Search.java
Labels: api: cloudasset, cla: yes, samples

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudasset, automerge, cla: yes

#523 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: cloudasset, automerge, cla: yes, context: full

#524 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: cloudasset, automerge, cla: yes
