Repository googleapis/java-asset, pull requests merged in 2021-09, with the labels that each got.

#894 chore: remove strict status checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudasset

#882 samples: Add relationship and per-type bigquery samples to Cloud Asset service
  samples/snippets/src/main/java/com/example/asset/CreateFeedExample.java
  samples/snippets/src/main/java/com/example/asset/ExportAssetsBigqueryExample.java
  samples/snippets/src/main/java/com/example/asset/ExportAssetsExample.java
  samples/snippets/src/main/java/com/example/asset/ListAssetsExample.java
  samples/snippets/src/test/java/com/example/asset/ListAssets.java
  samples/snippets/src/test/java/com/example/asset/QuickStartIT.java
  samples/snippets/src/test/java/com/example/asset/RealTimeFeed.java
Labels: cla: yes, api: cloudasset, samples

#897 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudasset, automerge

#907 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: cloudasset, automerge

#911 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: cloudasset, automerge

#929 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: cloudasset, automerge

#951 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: cloudasset
